### ISSUE TITLE
Enemy Units

### ISSUE THREAD

**Issue by squidinkettle** [livinineighties/SummerProject2019#41]
1. Will spawn at a game object named "Enemy Spawn"
2. Will either gather up at a game object called "Key Point" or go straight to the player and attack
3. Once close to the player, it will attack once every 5 seconds and it will have a 5% chance of damaging the dragon

**Comment by squidinkettle** [comment]
All of these are done, will need to work on the pathfinding eventually

**Comment by squidinkettle** [comment]
Units finally have a decent pathfinding.

They attack once every 5 seconds and have a 5% of damaging the dragon

Units have 3 modes:
*When spawn, head toward the dragon and attack
*Head towards an area and defend it
*Spawn only when the dragon is nearby, ambushing it

**Comment by 357Mike** [comment]
Great work! Thanks for the update!
